config/routes.rb
Youtube::Application.routes.draw do
  match 'youtubes/video_validator' => 'youtubes#video_validator', :as => :video_validator, :via => :post
  match 'youtubes/video_validator' => 'youtubes#video_validator', :as => :video_validator, :via => :get
  root :to => "youtubes#index"

end

app/models/video.rb
class Video < ActiveRecord::Base
		validates :youtube_id, :presence => true, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/youtubes_controller.rb
#~ require 'youtube_it'
#~ require 'uri'

class YoutubesController < ApplicationController
		def video_validator
				@status, @message = youtube_url_validator				
				render 'index'
		end		
		
		def youtube_url_validator
				if params[:yt_url].blank?# || params[:yt_url].length != 11
						return false, "Url cannot be blank"
				else
						video_id = extract_video_id
						if video_id
								client = YouTubeIt::Client.new
								begin
										client.video_by(video_id)
										Video.create(:youtube_id => video_id, :is_valid => true)
										return true, "Video found"
								rescue OpenURI::HTTPError
										#~ Video.create(:youtube_id => video_id)
										return false, "Video not found"										
								end
						else
								return false, "Invalid youtube url"
						end						
				end				
		end		
		
		def extract_video_id
				begin
						uri = URI(params[:yt_url])
						params = uri.query.split("&")
						v_param = params.find {|p| p.include?("v=")}
						return v_param.split("v=").last
				rescue
						return nil
				end
		end
		
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/youtubes_helper.rb
module YoutubesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Youtube</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag params[:controller] %>
  <%= javascript_include_tag params[:controller] %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="page-header">
    <h1>Youtube Url Tester</h1>
  </div>
  <%= yield %>

</body>
</html>

app/views/youtubes/index.html.erb
<%= form_tag(video_validator_path, :class => "navbar-search pull-left") do -%>
		<%= text_field_tag "yt_url", params[:yt_url] || '', :style => "width: 350px;", :class => "search-query", :placeholder => "Enter URL here.." -%>
<% end %>

<br />
<br />
<br />
<% if !@message.blank? %>
		<div class="alert <%= @status ? "alert-success" : "alert-error" %>">
				<button type="button" class="close" data-dismiss="alert">x</button>
				<%= @message %>
		</div>
<% end %>
<% if 1==2 %>
		<br />
		<br />
		<br />
		Params:
		<div class="alert alert-info">
				<%= params.to_json %>
		</div>
<% end %>